### ISSUE TITLE
slide/pengertian

### ISSUE THREAD

**Issue by leticiakosasih00** [181114141/Tugas-TKPPL-Kelompok-2#2]
deadline 08/1/2022

**Comment by 181113031Gilbert** [comment]
Slide pengertian sudah selesai, berikut referensi atau sumber yang di gunakan :

https://id.reactjs.org/
https://www.niagahoster.co.id/blog/react-js-adalah/
https://socs.binus.ac.id/2019/12/30/apa-itu-react-js/

**Comment by leticiakosasih00** [comment]
done merge to main
